POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
POWERLEVEL9K_INSTANT_PROMPT=verbose
POWERLEVEL9K_DISABLE_HOT_RELOAD=true

# battery
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='46'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='235'
POWERLEVEL9K_BATTERY_CHARGED_ICON=' '
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='178'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='235'
POWERLEVEL9K_BATTERY_CHARGING_ICON=' '
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='203'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='245'
POWERLEVEL9K_BATTERY_LOW_ICON=' '
POWERLEVEL9K_BATTERY_DISCONNECTED='$DEFAULT_COLOR'
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_BATTERY_ICON=' '

# public_ip
POWERLEVEL9K_PUBLIC_IP_ICON=' '

# vpn_ip
POWERLEVEL9K_VPN_IP_ICON='󰖂 '

# time
POWERLEVEL9K_TIME_FORMAT="%D{%m.%d %H:%M}"
POWERLEVEL9K_TIME_ICON='󱑍'

# background_jobs
POWERLEVEL9K_BACKGROUND_JOBS_ICON=''

# command_execution_time
POWERLEVEL9K_EXECUTION_TIME_ICON='󱎫'

# status
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_CROSS=true

# USER
POWERLEVEL9K_ALWAYS_SHOW_USER=true
POWERLEVEL9K_CONTEXT_TEMPLATE="%n"
POWERLEVEL9K_CONTEXT_FOREGROUND='white'

# dir
POWERLEVEL9K_DIR_BACKGROUND='blue'

# prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ICON_LEFT=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context root_indicator dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs vpn_ip public_ip time battery)

# prompt prefix
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F\uE0B6"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} "
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%b%f%k%F{blue}%} %{%f%}" POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX="%F{blue}\uF47D\u2500\u256E" \uf459
POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX="%F{blue}\uE0B4\u256F"
