POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
POWERLEVEL9K_INSTANT_PROMPT=verbose
POWERLEVEL9K_DISABLE_HOT_RELOAD=true

# battery
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='green1'
POWERLEVEL9K_BATTERY_CHARGED_ICON=' '
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='gold3'
POWERLEVEL9K_BATTERY_CHARGING_ICON=' '
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='black'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='indianred'
POWERLEVEL9K_BATTERY_LOW_ICON=' '
POWERLEVEL9K_BATTERY_DISCONNECTED='$DEFAULT_COLOR'
POWERLEVEL9K_BATTERY_FOREGROUND='white'
POWERLEVEL9K_BATTERY_BACKGROUND='#45475A'
POWERLEVEL9K_BATTERY_ICON=' '

# public_ip
POWERLEVEL9K_PUBLIC_IP_ICON=' '
POWERLEVEL9K_PUBLIC_IP_FOREGROUND='white'
POWERLEVEL9K_PUBLIC_IP_BACKGROUND='#45475A'

# vpn_ip
POWERLEVEL9K_VPN_IP_ICON='󰖂 '

# time
POWERLEVEL9K_TIME_FORMAT="%D{%m.%d %H:%M}"
POWERLEVEL9K_TIME_ICON='󱑍'

# background_jobs
POWERLEVEL9K_BACKGROUND_JOBS_ICON=''

# command_execution_time
POWERLEVEL9K_EXECUTION_TIME_ICON='󱎫'

# status
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_CROSS=true

# os icon
POWERLEVEL9K_OS_ICON_FOREGROUND='white'
POWERLEVEL9K_OS_ICON_BACKGROUND='#45475A'

# USER
POWERLEVEL9K_ALWAYS_SHOW_USER=true
POWERLEVEL9K_CONTEXT_TEMPLATE="%n"
POWERLEVEL9K_CONTEXT_FOREGROUND='white'
POWERLEVEL9K_CONTEXT_BACKGROUND='#45475A'

# dir
POWERLEVEL9K_DIR_BACKGROUND='blue'

# prompt
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ICON_LEFT=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context root_indicator dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs vpn_ip public_ip time battery)

# prompt prefix
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}╭─%F{#45475A}"
 POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}╰%F{white} "
 POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX="%F{#45475A}"
