-- Conky, a system monitor https://github.com/brndnmtthws/conky
--
-- This configuration file is Lua code. You can write code in here, and it will
-- execute when Conky loads. You can use it to generate your own advanced
-- configurations.
--
-- Try this (remove the `--`):
--
--   print("Loading Conky config")
--
-- For more on Lua, see:
-- https://www.lua.org/pil/contents.html

conky.config = {
    update_interval = 1.5,  -- update interval in seconds
    xinerama_head = 0,      -- for multi monitor setups, select monitor to run on: 0,1,2
    double_buffer = true,   -- use double buffering (reduces flicker, may not work for everyone)

    -- sensor sample
    cpu_avg_samples = 2,
    net_avg_samples = 2,

    -- output configuration
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,

    -- window alignment
    alignment = 'top_left',
    gap_x = 60,
    gap_y = 8,

    -- window settings
    minimum_width = 5,            -- conky will add an extra pixel to this
    minimum_height = 5,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',  -- values: desktop (background), panel (bar)
    own_window_hints = 'undecorated,skip_taskbar,skip_pager',

    -- window borders
    draw_borders = false,     -- draw borders around the conky window
    border_width = 16,         -- width of border window in pixels
    border_inner_margin = 0,  -- margin between the border and text in pixels
    border_outer_margin = 0,  -- margin between the border and the edge of the window in pixels

    -- transparency configuration
    draw_blended = false,
    own_window_transparent = false,  -- if own_window_argb_visual is true sets background opacity 0%
    own_window_argb_visual = true,  -- turn on transparency
    own_window_argb_value = 120,    -- 0-255
    own_window_colour = '#1E1E2E',  -- set colour if own_window_transparent no

    -- miscellanous settings
    background = false,
    imlib_cache_flush_interval = 250,
    if_up_strictness = 'address',
    format_human_readable = true,  -- KiB, MiB rather then number of bytes
    short_units = true,	           -- shorten units from KiB to k

    -- font settings
    use_xft = true,
    draw_shades = false,      -- black shadow on text (not good if text is black)
    draw_outline = false,     -- black outline around text (not good if text is black)
    font = 'DejaVu Sans Mono:size=12',

    -- colors
    default_color = '#CDD6F4',  -- text
    color1 = '#FAB387',         -- peach
    color2 = '#F9E2AF'          -- yellow
}

conky.text = [[
${color white}${font DejaVu:size=100}${alignc}${time %H}:${time %M}${font}
${color white}${font DejaVu:size=24}${alignc}${time %Y}-${time %m}-${time %d} (${time %a}) ${font}

${color2}${font DejaVu:style=Bold:size=16}C P U   ${hr 2}${font}
${color}CPU Frequency:${alignr}${freq}MHz
${color}CPU Usage:${alignr}${cpu}%
${cpugraph cpu0}

${color2}${font DejaVu:style=Bold:size=16}M E M O R Y   ${hr 2}${font}
${color}Swap Usage:${alignr}${swap}/${swapmax}
${color}Memory Usage:${alignr}${mem}/${memmax}
${memgraph}

${color2}${font DejaVu:style=Bold:size=16}N E T W O R K   ${hr 2}${font}
${color}Default Gateway:${alignr}${gw_ip}
${color}External IP Address:${alignr}${texeci 3600 wget -q -O- https://ipecho.net/plain}

${color2}${font DejaVu:style=Bold:size=16}G P U   ${hr 2}${font}
${color}GPU Utilization:${alignr}${exec nvidia-smi --query-gpu=utilization.gpu --format=noheader,nounits}%
${color}VRAM Usage:${alignr}${exec nvidia-smi --query-gpu=memory.used --format=noheader,nounits} MB/${exec nvidia-smi --query-gpu=memory.total --format=noheader,nounits} MB
]]
